// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG5nptBWwkYL8T766VrqkM8wD57urLQuM',
    appId: '1:769773117730:web:c2302c5c06f6e99968857b',
    messagingSenderId: '769773117730',
    projectId: 'spacey-3c942',
    authDomain: 'spacey-3c942.firebaseapp.com',
    storageBucket: 'spacey-3c942.firebasestorage.app',
    measurementId: 'G-457WTR5X6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNb9w1xY0dJ0x00tHQhkyQscuobN1BhQ',
    appId: '1:769773117730:android:d5aabfbf8d8cbbe868857b',
    messagingSenderId: '769773117730',
    projectId: 'spacey-3c942',
    storageBucket: 'spacey-3c942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDg4NaUWY-VIhHS5iV2jowb2JBmRRa2s',
    appId: '1:769773117730:ios:8f7118380e6f009868857b',
    messagingSenderId: '769773117730',
    projectId: 'spacey-3c942',
    storageBucket: 'spacey-3c942.firebasestorage.app',
    iosBundleId: 'com.example.spacey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXDg4NaUWY-VIhHS5iV2jowb2JBmRRa2s',
    appId: '1:769773117730:ios:8f7118380e6f009868857b',
    messagingSenderId: '769773117730',
    projectId: 'spacey-3c942',
    storageBucket: 'spacey-3c942.firebasestorage.app',
    iosBundleId: 'com.example.spacey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG5nptBWwkYL8T766VrqkM8wD57urLQuM',
    appId: '1:769773117730:web:f3d5cdc46ce2313c68857b',
    messagingSenderId: '769773117730',
    projectId: 'spacey-3c942',
    authDomain: 'spacey-3c942.firebaseapp.com',
    storageBucket: 'spacey-3c942.firebasestorage.app',
    measurementId: 'G-42CMGNQK0V',
  );
}
